[package]
name = "reql"
description = "A native RethinkDB driver"
version = "0.0.6-alpha7"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]
build = "build/main.rs"

[badges]
travis-ci = { repository = "rust-rethinkdb/reql" }
appveyor = { repository = "rust-rethinkdb/reql" }

[features]
default = ["with_io"]
with_io = ["reql-io"]

[dependencies]
protobuf = "1.1"
slog = "1.5"
serde_json = "0.9"
ql2 = "1.1"
derive-error = "0.0.3"
reql-derive = { version = "0.0.6-alpha4", path = "./derive" }
reql-io = { version = "0.2", path = "./io", optional = true }

[dev-dependencies]
slog-term = "1.5"

[build-dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_yaml = "0.6"
quote = "0.3"
syn = "0.11"
