[package]
name = "reql"
description = "A native RethinkDB driver"
version = "0.0.5"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

build = "build.rs"

[dependencies]
ql2 = { path = "/home/enchanter/projects/ql2" }
r2d2 = "0.7"
futures = "0.1"
slog = { version = "1.2", features = ["release_max_level_warn"] }
slog-term = "1.0"
lazy_static = "0.2"
parking_lot = "0.3"

[build-dependencies]
skeptic = "0.6"
serde_codegen = "0.8"

[dev-dependencies]
skeptic = "0.6"
