[package]
name = "reql"
description = "A native RethinkDB driver"
version = "0.0.6-alpha1"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-rethinkdb/reql"
documentation = "https://docs.rs/reql/*/reql/commands/"
readme = "README.md"
keywords = ["database", "rethinkdb", "reql", "driver"]
categories = ["database"]
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
ql2 = "1.1"
protobuf = "1.1"
slog = { version = "1.2", features = ["release_max_level_warn"] }
serde_json = "0.9"
derive-error = "0.0.3"
reql-derive = { path = "./reql-derive" }

[dev-dependencies]
rspec = "1.0.0-beta.3"
slog-term = "1.4"

[badges]
travis-ci = { repository = "rust-rethinkdb/reql" }
