[package]
name = "reql-derive"
description = "An implementation of the args macro used by the reql crate"
version = "0.0.7"
license = "MIT/Apache-2.0"
repository = "https://github.com/rethinkdb-rs/reql"
authors = ["rushmorem <rushmore@webenchanter.com>"]

[dependencies]
syn = "0.11"
quote = "0.3"
proc-macro-hack = "0.4"

[lib]
proc-macro = true
