[package]
name = "blocking"
version = "0.1.0"
authors = ["rushmorem <rushmore@webenchanter.com>"]
publish = false

[[bin]]
name = "blocking"
path = "main.rs"

[dependencies]
reql = { path = "../.." }
reql-types = { path = "../../types" }
futures = "0.1"
